server:
  port: 7700

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
    id: dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 27700
  registry:
    id: local
    protocol: zookeeper
    address: 10.211.81.43:2181
  scan:
    base-packages: com.dxk.provider.service.impl
